### ISSUE TITLE
Texture normal have unexpected effects

### ISSUE THREAD

**Issue by mwestphal** [f3d-app/f3d#2556]
**Describe the bug**
When added a normal texture F3D behave unexpectedly

**To Reproduce**

1. download: https://github.com/user-attachments/assets/bf59faaf-323b-4437-984f-12451e9df447
2.  `f3d WaterBottle.glb --texture-normal=~/data/tmp/UVChecker2048.png` 

<img width="1000" height="600" alt="Image" src="https://github.com/user-attachments/assets/5cd61dd9-e425-4daf-a78a-5f2aa104dc3a" />

**Expected behavior**
Should impact the normals instead.

**System Information:**

- OS: Any
- GPU and GPU driver: Any

**F3D Information**
Paste the content of `f3d --version` or `f3d-console.exe --version` on Windows: 3.2.0

**Comment by AoGao-Kedoka** [comment]
I believe this is already fixed? This is how it looks like for me on linux.
`./bin/f3d ../testing/data/WaterBottle.glb --texture-normal=~/data/normal.png`
<img width="957" height="1050" alt="Image" src="https://github.com/user-attachments/assets/79853f07-dcd1-4087-ab2c-d16858cb1e01" />

**Comment by mwestphal** [comment]
> I believe this is already fixed? This is how it looks like for me on linux. `./bin/f3d ../testing/data/WaterBottle.glb --texture-normal=~/data/normal.png` <img alt="Image" width="957" height="1050" src="https://private-user-images.githubusercontent.com/58142398/514769894-79853f07-dcd1-4087-ab2c-d16858cb1e01.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMyMzA2MTMsIm5iZiI6MTc2MzIzMDMxMywicGF0aCI6Ii81ODE0MjM5OC81MTQ3Njk4OTQtNzk4NTNmMDctZGNkMS00MDg3LWFiMmMtZDE2ODU4Y2IxZTAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE1VDE4MTE1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMTk0ZGYxMTE5MTNjMWJkMmE4Y2YzZjFhNTBjMWZjM2RhYjQ1YjEzNTAzNTBiZDgzZTMzOWMwYjIzZDhhOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hGX7IaP3ndGZ_Y7k1Ds1jhFTwdhqPr3wPr0AG1FETI0">

Well, you have the same results as me, so clearly not fixed :)

But maybe @Meakk have more inputs.

**Comment by AoGao-Kedoka** [comment]
ok, i thought it's about the normal texture not applied to the black bottle holder part. 
This is the result I get from blender. I'm not sure what's the expected result then.
<img width="1289" height="977" alt="Image" src="https://github.com/user-attachments/assets/819bfee0-d1aa-48d2-bdaa-603804aec546" />

**Comment by Meakk** [comment]
I agree with @AoGao-Kedoka there is no issue I believe. Normal textures encodes the normal deviation in tangent space. Giving any color texture in input which definitely not encodes normalized vectors in tangent space will always give unexpected results.  
Closing this, thanks for the investigation @AoGao-Kedoka 👍
